### ISSUE TITLE
The last version of master does not compile

### ISSUE THREAD

**Issue by mvy** [prologin/metalang#1]
> ###### Originally posted 2015-04-17 13:51 by [mvy](https://bitbucket.org/mvy/) on Bitbucket

The lastest commit (9fcb5ff) does not allow for proper compilation on debian. 

```
nanocale[master]% make metalang
Finished, 0 targets (0 cached) in 00:00:00.
+ /usr/bin/ocamlc -c -g -annot -I Printers -I Stdlib -I Ast -I Main -I Eval -I Passesfun -I Passes -I Parser -I Astfun -o Printers/printer.cmo Printers/printer.ml
File "Printers/printer.ml", line 461, characters 37-68:
Error: This expression has type string but an expression was expected of type
         ('a, Format.formatter, unit) format =
           ('a, Format.formatter, unit, unit, unit, unit) format6
Command exited with code 2.
Compilation unsuccessful after building 28 targets (27 cached) in 00:00:07.
make: *** [main.byte] Error 10

```
The last change of this section has been introduced by commit [35c558d] as well as in many other files. 

Is this a problem of version ? 

```
nanocale[master]% ocamlc -v
The Objective Caml compiler, version 3.12.1
```

[1]: https://github.com/prologin/metalang/commit/35c558dc44dad7195a1a1b615857ee9db7da26c3

**Comment by coucou747** [comment]
> ###### Originally posted 2015-04-17 21:50 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

please use ocaml >= 4

**Comment by coucou747** [comment]
> ###### Originally posted 2015-04-17 21:50 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

it's not a bug.
you can install ocaml with OPAM, it will fix this issue.
