### ISSUE TITLE
Unclear error message for uppercase typo

### ISSUE THREAD

**Issue by Shloub** [prologin/metalang#4]
```
main
	print N
end
```

The error message for this metalang file is `Fatal error: exception Not_found`, which does not seem very clear to me.

Please note that if `N` were lowercase (`n`), then the message would be `Cannot find variable n (on test.metalang:2:6-7)` (looks much clearer to me).

**Comment by coucou747** [comment]
Fixed : d3ff0e014f52548f931cc8b76fe953bed1128897
